### PR TITLE
Display next to the event whether ghost supports the event

### PR DESCRIPTION
**Pull request by steve02081504**
https://ukadon.shillest.net/@steve02081504/110463127602654227

Run-time screenshot:
图片

### CODE REVIEW

**Review by nikolat — COMMENTED** [review]
It is taking a long time due to the large number of SSTP communications.
All information should be retrieved in a single SSTP.

**Comment by steve02081504** [comment]
> It is taking a long time due to the large number of SSTP communications. All information should be retrieved in a single SSTP.

I thought of this yesterday, but for some reason I thought yesterday that this might lead to some safety hazards
In hindsight I may have misjudged it
It'll be a while, I need to write something to finish this

**Comment by steve02081504** [comment]
> It is taking a long time due to the large number of SSTP communications. All information should be retrieved in a single SSTP.

fixed at https://github.com/ukatech/ukadoc/commit/bb81f8a5aeeceda0b1eb11fb02c3e4fd27b2fba3 and https://github.com/ukatech/jsstp-lib/commit/21a0dd51a96dcaf9eb74294aacf0deed772ce813 with https://github.com/Taromati2/ghost/commit/8be148e954ca4588558d72b7c7741d4fa2b4756c

**Review by nikolat — APPROVED** [review]
I think it's cool!👍
Thanks!

**Pull request merged**
